### ISSUE TITLE
[EHN] details to-do

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#173]
- [x] 회원가입/로그인/로그아웃 alert주기
- [x]  rest컨트롤러 -> api컨트롤러로 이름 변경
- [x] member 테이블: 학과,대학 저장할 칼럼&기능
- [x] member 대리키 추가(pk와 id분리)

**Comment by kimhanui** [comment]
Resolves (pr #180 )
