### ISSUE TITLE
[BUG] JSP 수정 요청 통합

### ISSUE THREAD

**Issue by 2kyung19** [riyenas0925/Sejong_Track_Management#225]
### jsp 수정 요청사항
> 한눈에 보기가 어려워서... 제 todo같은 겁니다

- [ ] 회원가입 페이지 (https://github.com/riyenas0925/Sejong_Track_Management/issues/221) : 학과,소속대학 더미값 / 이름 disabled
- [ ] 전체트랙 페이지 (https://github.com/riyenas0925/Sejong_Track_Management/issues/220) : 데이터값 api에서 뽑아오기/자동줄바꿈
- [ ] 내정보 페이지 (https://github.com/riyenas0925/Sejong_Track_Management/issues/219) : 학번 부분 제거
